import type { Metadata } from "next";
import { Fraunces, Work_Sans } from 'next/font/google'
import "./globals.css";

const fraunces = Fraunces({ subsets: ['latin'], variable: '--font-fraunces' })

const workSans = Work_Sans({ subsets: ['latin'], variable: '--font-work-sans' })

export const metadata: Metadata = {
  title: "Koreni - informacioni sistem",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      className={`${fraunces.variable} ${workSans.variable}`}
    >
      <body className="min-h-full flex flex-col">{children}</body>
    </html>
  );
}
